export const tips = [
  "You can set keybindings and explore advanced commands on the 'Commands' tab.",  
  "Nimble RPG App is in a beta state. Please periodically export your user data for safe keeping!",
  "You can follow your Encounter on any device with the Player View URL.",
  `Monsters and Heroes behave differently when added from the library. A Monster's Statblock is copied onto a single Combatant, which exists for the span of the Encounter. On the other hand, a Hero's Statblock is unique and persists its changes across different Encounters.`,
  `The "Edit Unique Statblock" Combatant Command lets you make ad-hoc changes to a single Combatant's statblock without affecting your Creature Library.`,
  "You can restore hit points by applying negative damage to a Combatant.",
  "Temporary hit points obey the Nimble RPG rules- applying temporary hitpoints will ignore temporary hit points a Combatant already has.",
  "Hidden Combatants can be added to the encounter by holding 'alt' when clicking their library entry.",
  "You can select multiple Combatants by holding a modifier key. You can apply damage or tags to multiple Combatants at the same time this way.",
  "Legendary Monsters enters combat with HP matching the amount of players.",
  "You can track the inventory of a Hero by enabling the Inventory feature in the Options tab. You can add items to a Hero's inventory by using the 'Add Item' Combatant Command.",
  "The Player View will only display a colored, qualitative indicator for NPC HP. You can change this in the settings tab.",
  "You can create Tags that disappear after a set amount of rounds in order to automatically remove conditions at the end of a Combatant's turn.",
  "You can get automatic Concentration reminders by using the tag 'Concentrating.' You can disable this feature in the settings.",
  "The Library Manager allows you to move, delete, or export multiple items at the same time. You can enable it in the Encounter Commands tab.",
  // "Want to contribute? Nimble RPG App is written in TypeScript and runs on node.js. Fork it on <a href='https://github.com/EddyWongGM/nimble-gm-tools' target='_blank'>GitHub.</a>",
  "Account Sync will let you access your Heroes and Encounters from any device. <a href='https://www.patreon.com/NimbleRPGApp' target='_blank'>Pledge on Patreon</a> to unlock this benefit!",
  "Epic Nimble RPG App will let you enhance your Player View with combatant portraits and custom colors. This Patreon tier is coming soon!",
  // "I also made <a href='http://paragondashboard.com' target='_blank'>Paragon Campaign Dashboard</a>, a powerful, customizable virtual GM screen and campaign prep app."
];
